//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandyStoreWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int ProID { get; set; }
        public Nullable<int> DepID { get; set; }
        public string ProNombre { get; set; }
        public string ProDescripcion { get; set; }
        public Nullable<double> ProValor { get; set; }
        public string ProRutaImagen { get; set; }
        public Nullable<System.DateTime> ProFechaCreacion { get; set; }
        public Nullable<System.DateTime> ProFechaActualizacion { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
    }
}
